# This is a basic workflow to help you get started with Actions
# https://canovasjm.netlify.app/2020/11/29/github-actions-run-a-python-script-on-schedule-and-commit-changes/

name: update-data

on:
  schedule:
    - cron: '0 10 * * *' # runs at 10:00 UTC everyday 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5' # install the python version needed
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/github.txt
      - name: execute py script # run update.py to get the latest data
        env: 
          SIMFIN_API_KEY: ${{ secrets.SIMFIN_API_KEY }}
        run: python update_data.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "updated model data" -a
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master